# Generated by Django 3.1 on 2020-09-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upstreams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50, verbose_name='path')),
                ('upstream', models.URLField(verbose_name='')),
            ],
        ),
    ]
